In [74]:
# panda dataframe
import pandas as pd

In [75]:
df = pd.read_csv('/Users/pinqingkan/OneDrive/JobSearch/DataScience/PythonDataScience/DAT210x-master/Module2/Datasets/direct_marketing.csv')
df

recency   history_segment  history  mens  womens   zip_code  newbie  \
0           10    2) $100 - $200   142.44     1       0  Surburban       0   
1            6    3) $200 - $350   329.08     1       1      Rural       1   
2            7    2) $100 - $200   180.65     0       1  Surburban       1   
3            9    5) $500 - $750   675.83     1       0      Rural       1   
4            2      1) $0 - $100    45.34     1       0      Urban       0   
5            6    2) $100 - $200   134.83     0       1  Surburban       0   
6            9    3) $200 - $350   280.20     1       0  Surburban       1   
7            9      1) $0 - $100    46.42     0       1      Urban       0   
8            9    5) $500 - $750   675.07     1       1      Rural       1   
9           10      1) $0 - $100    32.84     0       1      Urban       1   
10           7    5) $500 - $750   548.91     0       1      Urban       1   
11           1    3) $200 - $350   211.45     0       1      Urban       1   
12           5    5) $500 - $750   642.90     0       1  Surburban       1   
13           2    2) $100 - $200   101.64     0       1      Urban       0   
14           4    3) $200 - $350   241.42     0       1      Rural       1   
15           3      1) $0 - $100    58.13     1       0      Urban       1   
16           5      1) $0 - $100    29.99     1       0  Surburban       0   
17           9    2) $100 - $200   112.35     1       0      Rural       0   
18          11    3) $200 - $350   219.04     1       1  Surburban       0   
19           5  6) $750 - $1,000   828.42     1       0  Surburban       1   
20           9      1) $0 - $100    29.99     0       1  Surburban       1   
21          11    2) $100 - $200   182.32     1       0  Surburban       0   
22           2    2) $100 - $200   118.40     1       0  Surburban       0   
23           2      1) $0 - $100    29.99     0       1      Urban       1   
24           4      1) $0 - $100    78.24     1       0  Surburban       0   
25           6    2) $100 - $200   139.87     0       1      Rural       1   
26          12    2) $100 - $200   115.39     0       1  Surburban       0   
27           6    2) $100 - $200   162.98     0       1  Surburban       0   
28           7    4) $350 - $500   435.73     0       1      Urban       1   
29           2    3) $200 - $350   203.35     1       0      Rural       0   
...        ...               ...      ...   ...     ...        ...     ...   
63970        4    2) $100 - $200   191.15     0       1  Surburban       1   
63971        5    5) $500 - $750   549.87     0       1  Surburban       1   
63972        3    5) $500 - $750   554.97     0       1  Surburban       1   
63973        8    4) $350 - $500   471.80     1       0  Surburban       1   
63974        8      1) $0 - $100    73.65     0       1  Surburban       0   
63975       10  6) $750 - $1,000   883.92     1       0      Urban       1   
63976        1    5) $500 - $750   710.72     1       1      Urban       1   
63977        8      1) $0 - $100    29.99     0       1  Surburban       0   
63978       10    2) $100 - $200   102.01     0       1      Urban       1   
63979       10    2) $100 - $200   168.21     0       1  Surburban       0   
63980        3    4) $350 - $500   487.10     0       1  Surburban       1   
63981        4    2) $100 - $200   125.53     0       1      Rural       1   
63982        5      1) $0 - $100    29.99     1       0      Urban       1   
63983        2      1) $0 - $100    83.03     0       1      Urban       0   
63984        2    3) $200 - $350   209.51     0       1      Urban       1   
63985        9      1) $0 - $100    29.99     1       0      Urban       0   
63986        9      1) $0 - $100    35.26     0       1      Urban       1   
63987        1      1) $0 - $100    79.70     1       0  Surburban       1   
63988        6      1) $0 - $100    32.98     1       0  Surburban       0   
63989       10    3) $200 - $

In [76]:
df.mens.isnull()

0        False
1        False
2        False
3        False
4        False
5        False
6        False
7        False
8        False
9        False
10       False
11       False
12       False
13       False
14       False
15       False
16       False
17       False
18       False
19       False
20       False
21       False
22       False
23       False
24       False
25       False
26       False
27       False
28       False
29       False
         ...  
63970    False
63971    False
63972    False
63973    False
63974    False
63975    False
63976    False
63977    False
63978    False
63979    False
63980    False
63981    False
63982    False
63983    False
63984    False
63985    False
63986    False
63987    False
63988    False
63989    False
63990    False
63991    False
63992    False
63993    False
63994    False
63995    False
63996    False
63997    False
63998    False
63999    False
Name: mens, dtype: bool

In [6]:
# understand the index referencing of array
A = [1, 2, 3, 4]
A[0:1] # produce an array
A[0] # produce the value

In [25]:
# data slicing
B = df.loc[0:9,['zip_code']]
B

In [27]:
# convert to numbers: one array for each value
B = pd.get_dummies(B, columns = ['zip_code'])
B

In [17]:
# quick and dirty conversion
B.zip_code = B.zip_code.astype("category").cat.codes
B

In [12]:
# all texts transformation
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
# count the word in the texts
corpus = [
    "Authman ran faster than Harry because he is an athlete.",
    "Authman and harry ran faster and faster."
]
corpus

In [22]:
Y = CountVectorizer() # many properties to change
Y

In [24]:
X = Y.fit_transform(corpus)
X # sparse matrix
Y.get_feature_names() # show the words
X.toarray()

In [61]:
# image processing
from scipy import misc

In [62]:
img = misc.imread('/Users/pinqingkan/OneDrive/2017 Spring/Nunan/Fcor_Ou_is52.tif')

In [63]:
X = (img / 255.0).reshape(-1,3)
X # 1D array, colored

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [68]:
# 1D array, grey
red = X[:,0]
green = X[:,1]
blue = X[:,2]
Z = red*0.299 + green*0.587 + blue*0.114
Z

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [69]:
# 1D array, grey
Y = (img / 255.0).reshape(-1)
Y

array([ 1.,  1.,  1., ...,  1.,  1.,  1.])

In [56]:
# explore reshape
img.shape # (461, 588, 3)
X = (img / 255.0).reshape(461*588,3)
X

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       ..., 
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [44]:
# explore reshape
import numpy
a = numpy.array([ [1,2,3], [4,5,6] ])
a

In [47]:
numpy.reshape(a,6)

array([1, 2, 3, 4, 5, 6])

In [50]:
numpy.reshape(a,(1,6))

array([[1, 2, 3, 4, 5, 6]])

In [53]:
a.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])